// Generated by GitHub Copilot
import { act, render, screen, waitFor } from '@testing-library/react';
import { vi } from 'vitest';
import { AuthProvider, useAuth } from './AuthContext';
import axios from 'axios';

const {
  mockGetSession,
  mockOnAuthStateChange,
  mockSignOut,
  mockUnsubscribe
} = vi.hoisted(() => ({
  mockGetSession: vi.fn(),
  mockOnAuthStateChange: vi.fn(),
  mockSignOut: vi.fn(),
  mockUnsubscribe: vi.fn()
}));

vi.mock('../lib/supabase', () => ({
  supabase: {
    auth: {
      getSession: mockGetSession,
      onAuthStateChange: mockOnAuthStateChange,
      signOut: mockSignOut
    }
  }
}));

vi.mock('axios');

function Consumer() {
  const { user, loading, signOut } = useAuth();
  return (
    <div>
      <span data-testid="loading">{String(loading)}</span>
      <span data-testid="user">{user?.email ?? 'none'}</span>
      <button onClick={signOut}>Sign Out</button>
    </div>
  );
}

describe('AuthContext', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockOnAuthStateChange.mockReturnValue({
      data: { subscription: { unsubscribe: mockUnsubscribe } }
    });
  });

  test('initializes session and syncs user', async () => {
    mockGetSession.mockResolvedValue({
      data: {
        session: {
          access_token: 'token-abc',
          user: { email: 'hokie@vt.edu' }
        }
      },
      error: null
    });
    vi.mocked(axios.post).mockResolvedValue({ data: {} });

    render(
      <AuthProvider>
        <Consumer />
      </AuthProvider>
    );

    await waitFor(() => {
      expect(screen.getByTestId('user').textContent).toBe('hokie@vt.edu');
      expect(screen.getByTestId('loading').textContent).toBe('false');
    });

    expect(axios.post).toHaveBeenCalledWith(
      expect.stringContaining('/api/auth/sync'),
      {},
      expect.objectContaining({
        headers: expect.objectContaining({ Authorization: 'Bearer token-abc' })
      })
    );
  });

  test('handles auth state changes and syncs session user', async () => {
    mockGetSession.mockResolvedValue({ data: { session: null }, error: null });
    mockOnAuthStateChange.mockImplementation((cb) => ({
      data: { subscription: { unsubscribe: mockUnsubscribe } }
    }));
    vi.mocked(axios.post).mockResolvedValue({ data: {} });

    render(
      <AuthProvider>
        <Consumer />
      </AuthProvider>
    );

    await waitFor(() => {
      expect(mockOnAuthStateChange).toHaveBeenCalled();
    });

    const callback = mockOnAuthStateChange.mock.calls[0][0];

    await act(async () => {
      callback('SIGNED_IN', {
        access_token: 'token-xyz',
        user: { email: 'new@vt.edu' }
      });
    });

    await waitFor(() => {
      expect(screen.getByTestId('user').textContent).toBe('new@vt.edu');
      expect(axios.post).toHaveBeenCalled();
    });
  });

  test('signOut delegates to supabase auth signOut', async () => {
    mockGetSession.mockResolvedValue({ data: { session: null }, error: null });
    render(
      <AuthProvider>
        <Consumer />
      </AuthProvider>
    );

    screen.getByRole('button', { name: /sign out/i }).click();
    await waitFor(() => {
      expect(mockSignOut).toHaveBeenCalled();
    });
  });
});