// Generated by GitHub Copilot
const mockPool = jest.fn();
const mockPrismaPg = jest.fn();
const mockPrismaClient = jest.fn();

jest.mock('dotenv', () => ({
  config: jest.fn()
}));

jest.mock('pg', () => ({
  Pool: jest.fn((args) => {
    mockPool(args);
    return { _pool: true, args };
  })
}));

jest.mock('@prisma/adapter-pg', () => ({
  PrismaPg: jest.fn((pool) => {
    mockPrismaPg(pool);
    return { _adapter: true, pool };
  })
}));

jest.mock('@prisma/client', () => ({
  PrismaClient: jest.fn((options) => {
    mockPrismaClient(options);
    return { _client: true, options };
  })
}));

describe('prisma client setup', () => {
  beforeEach(() => {
    jest.resetModules();
    jest.clearAllMocks();
    process.env.DATABASE_URL = 'postgresql://user:pass@localhost:5432/testdb';
  });

  it('creates pool, adapter, prisma client, and exports prisma instance', () => {
    let prisma;

    jest.isolateModules(() => {
      prisma = require('./prisma');
    });

    expect(mockPool).toHaveBeenCalledWith({
      connectionString: 'postgresql://user:pass@localhost:5432/testdb'
    });
    expect(mockPrismaPg).toHaveBeenCalledWith(
      expect.objectContaining({ _pool: true })
    );
    expect(mockPrismaClient).toHaveBeenCalledWith({
      adapter: expect.objectContaining({ _adapter: true })
    });
    expect(prisma).toEqual(expect.objectContaining({ _client: true }));
  });
});