// Generated by GitHub Copilot
const mockUse = jest.fn();
const mockSet = jest.fn();
const mockGet = jest.fn();
const mockListen = jest.fn((port, cb) => cb());
const mockOn = jest.fn();

const mockApp = {
  use: mockUse,
  set: mockSet,
  get: mockGet
};

const mockIo = {
  on: mockOn
};

jest.mock('dotenv', () => ({
  config: jest.fn()
}));

jest.mock('cors', () => jest.fn(() => 'cors-middleware'));

jest.mock('http', () => ({
  createServer: jest.fn(() => ({
    listen: mockListen
  }))
}));

jest.mock('express', () => {
  const mockExpress = jest.fn(() => mockApp);
  mockExpress.json = jest.fn(() => 'json-middleware');
  mockExpress.static = jest.fn(() => 'static-middleware');
  return mockExpress;
});

jest.mock('socket.io', () => ({
  Server: jest.fn(() => mockIo)
}));

jest.mock('./routes/auth', () => 'auth-router');
jest.mock('./routes/rooms', () => 'rooms-router');
jest.mock('./routes/messages', () => 'messages-router');

describe('index bootstrap', () => {
  beforeEach(() => {
    jest.resetModules();
    jest.clearAllMocks();
    process.env.FRONTEND_URL = 'http://localhost:5173';
    process.env.PORT = '4444';
  });

  it('wires middleware, routes, sockets, and starts server', () => {
    jest.isolateModules(() => {
      require('./index');
    });

    expect(mockSet).toHaveBeenCalledWith('socketio', mockIo);
    expect(mockUse).toHaveBeenCalledWith('cors-middleware');
    expect(mockUse).toHaveBeenCalledWith('json-middleware');
    expect(mockUse).toHaveBeenCalledWith('/api/auth', 'auth-router');
    expect(mockUse).toHaveBeenCalledWith('/api/rooms', 'rooms-router');
    expect(mockUse).toHaveBeenCalledWith('/api/messages', 'messages-router');
    expect(mockGet).toHaveBeenCalledWith('/', expect.any(Function));
    expect(mockOn).toHaveBeenCalledWith('connection', expect.any(Function));
    expect(mockListen).toHaveBeenCalledWith('4444', expect.any(Function));
  });
});