// Generated by GitHub Copilot
const express = require('express');
const request = require('supertest');
const fs = require('fs');
const path = require('path');

jest.mock('../lib/prisma', () => ({
	message: { create: jest.fn(), findUnique: jest.fn() },
	reaction: { upsert: jest.fn() }
}));

jest.mock('../middleware/auth', () => (req, res, next) => {
	req.user = { id: 'user-1' };
	next();
});

const prisma = require('../lib/prisma');
const messagesRouter = require('./messages');

function createApp() {
	const app = express();
	app.use(express.json());
	app.set('socketio', { to: jest.fn(() => ({ emit: jest.fn() })) });
	app.use('/api/messages', messagesRouter);
	return app;
}

describe('messages routes', () => {
	beforeAll(() => {
		fs.mkdirSync(path.join(process.cwd(), 'uploads'), { recursive: true });
	});

	beforeEach(() => {
		jest.clearAllMocks();
	});

	it('POST /api/messages creates a message', async () => {
		prisma.message.create.mockResolvedValue({
			id: 'm1',
			content: 'hello',
			room_crn: '12345',
			attachments: [],
			reactions: [],
			user: { id: 'user-1', username: 'alice' }
		});

		const res = await request(createApp())
			.post('/api/messages')
			.field('content', 'hello')
			.field('room_crn', '12345');

		expect(res.status).toBe(200);
		expect(res.body.id).toBe('m1');
		expect(prisma.message.create).toHaveBeenCalledWith(
			expect.objectContaining({
				data: expect.objectContaining({
					content: 'hello',
					room_crn: '12345',
					user_id: 'user-1'
				})
			})
		);
	});

	it('POST /api/messages/:id/react upserts reaction and returns it', async () => {
		prisma.reaction.upsert.mockResolvedValue({
			message_id: 'm1',
			user_id: 'user-1',
			emoji: '👍'
		});
		prisma.message.findUnique.mockResolvedValue({
			id: 'm1',
			room_crn: '12345',
			user: { id: 'user-1', username: 'alice' },
			attachments: [],
			reactions: []
		});

		const res = await request(createApp())
			.post('/api/messages/m1/react')
			.send({ emoji: '👍' });

		expect(res.status).toBe(200);
		expect(res.body).toEqual({
			message_id: 'm1',
			user_id: 'user-1',
			emoji: '👍'
		});
	});

	it('POST /api/messages returns 500 when create fails', async () => {
		const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
		prisma.message.create.mockRejectedValue(new Error('db error'));

		const res = await request(createApp())
			.post('/api/messages')
			.field('content', 'hello')
			.field('room_crn', '12345');

		expect(res.status).toBe(500);
		expect(res.body).toEqual({ error: 'Failed to send message' });
		consoleErrorSpy.mockRestore();
	});

	it('POST /api/messages/:id/react returns 500 when upsert fails', async () => {
		const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
		prisma.reaction.upsert.mockRejectedValue(new Error('db error'));

		const res = await request(createApp())
			.post('/api/messages/m1/react')
			.send({ emoji: '👍' });

		expect(res.status).toBe(500);
		expect(res.body).toEqual({ error: 'Failed to react to message' });
		consoleErrorSpy.mockRestore();
	});
});
