// Generated by GitHub Copilot
const express = require('express');
const request = require('supertest');

jest.mock('../lib/prisma', () => ({
	user: { findUnique: jest.fn() },
	cRN_Room: { upsert: jest.fn(), findUnique: jest.fn() },
	user_CRN_Room: { upsert: jest.fn(), update: jest.fn(), delete: jest.fn() },
	message: { findMany: jest.fn() }
}));

jest.mock('../middleware/auth', () => (req, res, next) => {
	req.user = { id: 'user-1' };
	next();
});

const prisma = require('../lib/prisma');
const roomsRouter = require('./rooms');

function createApp() {
	const app = express();
	app.use(express.json());
	app.use('/api/rooms', roomsRouter);
	return app;
}

describe('rooms routes', () => {
	beforeEach(() => {
		jest.clearAllMocks();
	});

	it('GET /api/rooms formats user rooms with latest message', async () => {
		prisma.user.findUnique.mockResolvedValue({
			rooms: [
				{
					color: '#3b82f6',
					room: {
						crn: '12345',
						course_name: 'CS 3704',
						messages: [
							{
								content: 'hello class',
								created_at: '2026-04-22T12:00:00.000Z',
								user: { username: 'alice' }
							}
						]
					}
				}
			]
		});

		const res = await request(createApp()).get('/api/rooms');

		expect(res.status).toBe(200);
		expect(res.body).toEqual([
			{
				crn: '12345',
				course_name: 'CS 3704',
				color: '#3b82f6',
				latestMessage: {
					content: 'hello class',
					created_at: '2026-04-22T12:00:00.000Z',
					user: { username: 'alice' }
				}
			}
		]);
	});

	it('GET /api/rooms returns empty list when user not found', async () => {
		prisma.user.findUnique.mockResolvedValue(null);

		const res = await request(createApp()).get('/api/rooms');

		expect(res.status).toBe(200);
		expect(res.body).toEqual([]);
	});

	it('POST /api/rooms/join validates missing crn', async () => {
		const res = await request(createApp()).post('/api/rooms/join').send({});

		expect(res.status).toBe(400);
		expect(res.body).toEqual({ error: 'CRN is required' });
	});

	it('POST /api/rooms/join creates membership', async () => {
		prisma.cRN_Room.upsert.mockResolvedValue({});
		prisma.user_CRN_Room.upsert.mockResolvedValue({ user_id: 'user-1', crn: '12345' });

		const res = await request(createApp())
			.post('/api/rooms/join')
			.send({ crn: '12345', course_name: 'CS 3704' });

		expect(res.status).toBe(200);
		expect(prisma.cRN_Room.upsert).toHaveBeenCalled();
		expect(prisma.user_CRN_Room.upsert).toHaveBeenCalledWith(
			expect.objectContaining({
				where: {
					user_id_crn: {
						user_id: 'user-1',
						crn: '12345'
					}
				}
			})
		);
	});

	it('PATCH /api/rooms/:crn/color updates color preference', async () => {
		prisma.user_CRN_Room.update.mockResolvedValue({
			user_id: 'user-1',
			crn: '12345',
			color: '#ef4444'
		});

		const res = await request(createApp())
			.patch('/api/rooms/12345/color')
			.send({ color: '#ef4444' });

		expect(res.status).toBe(200);
		expect(res.body.color).toBe('#ef4444');
	});

	it('DELETE /api/rooms/:crn leaves room successfully', async () => {
		prisma.user_CRN_Room.delete.mockResolvedValue({});

		const res = await request(createApp()).delete('/api/rooms/12345');

		expect(res.status).toBe(200);
		expect(res.body).toEqual({ success: true });
	});

	it('GET /api/rooms/:crn/messages returns room messages', async () => {
		prisma.message.findMany.mockResolvedValue([{ id: 'm1', room_crn: '12345' }]);

		const res = await request(createApp()).get('/api/rooms/12345/messages');

		expect(res.status).toBe(200);
		expect(res.body).toEqual([{ id: 'm1', room_crn: '12345' }]);
	});

	it('GET /api/rooms/:crn/users returns room users', async () => {
		prisma.cRN_Room.findUnique.mockResolvedValue({
			users: [{ user: { id: 'u1', username: 'alice' } }]
		});

		const res = await request(createApp()).get('/api/rooms/12345/users');

		expect(res.status).toBe(200);
		expect(res.body).toEqual([{ id: 'u1', username: 'alice' }]);
	});

	it('GET /api/rooms returns 500 on prisma failure', async () => {
		prisma.user.findUnique.mockRejectedValue(new Error('db error'));

		const res = await request(createApp()).get('/api/rooms');

		expect(res.status).toBe(500);
		expect(res.body).toEqual({ error: 'Failed to fetch rooms' });
	});
});
