// Generated by GitHub Copilot
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { vi } from 'vitest';
import ChatPage from './ChatPage';
import axios from 'axios';

const { socketHandlers, mockSocket } = vi.hoisted(() => {
  const handlers: Record<string, (payload: any) => void> = {};
  const socket = {
    connect: vi.fn(),
    disconnect: vi.fn(),
    emit: vi.fn(),
    on: vi.fn((event: string, handler: (payload: any) => void) => {
      handlers[event] = handler;
    }),
    off: vi.fn()
  };

  return { socketHandlers: handlers, mockSocket: socket };
});

const mockAuthSession = {
  access_token: 'token-123',
  user: { id: 'u1', email: 'hokie@vt.edu' }
};

vi.mock('../context/AuthContext', () => ({
  useAuth: () => ({
    session: mockAuthSession
  })
}));

vi.mock('../lib/socket', () => ({ socket: mockSocket }));
vi.mock('axios');

function renderChatPage() {
  return render(
    <MemoryRouter initialEntries={['/chat/3704']}>
      <Routes>
        <Route path="/chat/:crn" element={<ChatPage />} />
      </Routes>
    </MemoryRouter>
  );
}

describe('ChatPage', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    Object.defineProperty(Element.prototype, 'scrollIntoView', {
      configurable: true,
      value: vi.fn()
    });
    Object.keys(socketHandlers).forEach((key) => delete socketHandlers[key]);

    vi.mocked(axios.get).mockImplementation((url: string) => {
      if (url.includes('/api/rooms/3704/messages')) {
        return Promise.resolve({
          data: [
            {
              id: 'm1',
              room_crn: '3704',
              user_id: 'u1',
              content: 'hello world',
              created_at: '2026-04-24T12:00:00.000Z',
              user: { id: 'u1', username: 'Hokie', avatar_url: null, last_seen: '' },
              attachments: [],
              reactions: [{ id: 'r1', emoji: '👍', user_id: 'u1' }]
            }
          ]
        });
      }

      if (url.includes('/api/rooms/3704/users')) {
        return Promise.resolve({
          data: [{ id: 'u1', username: 'Hokie', avatar_url: null, last_seen: '' }]
        });
      }

      return Promise.resolve({ data: { crn: '3704', course_name: 'CS 3704' } });
    });
  });

  test('fetches room data and joins socket room on mount', async () => {
    renderChatPage();

    expect(await screen.findByText('CS 3704')).toBeInTheDocument();
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/rooms/3704'), expect.any(Object));
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/rooms/3704/messages'), expect.any(Object));
    expect(axios.get).toHaveBeenCalledWith(expect.stringContaining('/api/rooms/3704/users'), expect.any(Object));
    expect(mockSocket.emit).toHaveBeenCalledWith('join_room', '3704');
  });

  test('react action posts reaction to backend', async () => {
    vi.mocked(axios.post).mockResolvedValue({ data: {} });
    renderChatPage();

    await screen.findByText('hello world');
    fireEvent.click(screen.getByRole('button', { name: /👍1/i }));

    await waitFor(() => {
      expect(axios.post).toHaveBeenCalledWith(
        expect.stringContaining('/api/messages/m1/react'),
        { emoji: '👍' },
        expect.any(Object)
      );
    });
  });

  test('handles socket new_message event by appending message', async () => {
    renderChatPage();
    await screen.findByText('hello world');

    socketHandlers.new_message({
      id: 'm2',
      room_crn: '3704',
      user_id: 'u2',
      content: 'new socket message',
      created_at: '2026-04-24T13:00:00.000Z',
      user: { id: 'u2', username: 'Alex', avatar_url: null, last_seen: '' },
      attachments: [],
      reactions: []
    });

    expect(await screen.findByText('new socket message')).toBeInTheDocument();
  });

  test('chat input sends message payload', async () => {
    vi.mocked(axios.post).mockResolvedValue({ data: {} });
    renderChatPage();
    await screen.findByText('hello world');

    fireEvent.change(screen.getByPlaceholderText('Message class...'), {
      target: { value: 'posting from test' }
    });

    fireEvent.submit(screen.getByPlaceholderText('Message class...').closest('form')!);

    await waitFor(() => {
      expect(axios.post).toHaveBeenCalledWith(
        expect.stringContaining('/api/messages'),
        expect.any(FormData),
        expect.any(Object)
      );
    });
  });
});
