// Generated by GitHub Copilot
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { vi } from 'vitest';
import DashboardPage from './DashboardPage';
import axios from 'axios';

const mockSignOut = vi.fn();

vi.mock('../context/AuthContext', () => ({
  useAuth: () => ({
    session: {
      access_token: 'token-123',
      user: { email: 'hokie@vt.edu' }
    },
    signOut: mockSignOut
  })
}));

vi.mock('axios');

describe('DashboardPage', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(window, 'prompt').mockReset();
    vi.spyOn(window, 'confirm').mockReset();
    vi.mocked(axios.get).mockResolvedValue({ data: [] });
  });

  test('fetches rooms on mount and renders room card', async () => {
    vi.mocked(axios.get).mockResolvedValue({
      data: [
        {
          crn: '3704',
          course_name: 'CS 3704',
          color: '#3b82f6',
          latestMessage: null
        }
      ]
    });

    render(
      <MemoryRouter>
        <DashboardPage />
      </MemoryRouter>
    );

    expect(await screen.findByText('CS 3704')).toBeInTheDocument();
    expect(axios.get).toHaveBeenCalledWith(
      expect.stringContaining('/api/rooms'),
      expect.objectContaining({
        headers: expect.objectContaining({ Authorization: 'Bearer token-123' })
      })
    );
  });

  test('join class posts room join and refetches rooms', async () => {
    vi.mocked(window.prompt)
      .mockReturnValueOnce('12345')
      .mockReturnValueOnce('CS 1234');
    vi.mocked(axios.post).mockResolvedValue({ data: {} });

    render(
      <MemoryRouter>
        <DashboardPage />
      </MemoryRouter>
    );

    fireEvent.click(await screen.findByRole('button', { name: /join class/i }));

    await waitFor(() => {
      expect(axios.post).toHaveBeenCalledWith(
        expect.stringContaining('/api/rooms/join'),
        { crn: '12345', course_name: 'CS 1234' },
        expect.any(Object)
      );
    });

    expect(vi.mocked(axios.get).mock.calls.length).toBeGreaterThanOrEqual(2);
  });

  test('leave room calls delete when confirmed', async () => {
    vi.mocked(axios.get).mockResolvedValue({
      data: [{ crn: '3704', course_name: 'CS 3704', color: '#3b82f6', latestMessage: null }]
    });
    vi.mocked(window.confirm).mockReturnValue(true);
    vi.mocked(axios.delete).mockResolvedValue({ data: {} });

    render(
      <MemoryRouter>
        <DashboardPage />
      </MemoryRouter>
    );

    await screen.findByText('CS 3704');
    const buttons = screen.getAllByRole('button');
    fireEvent.click(buttons[2]);
    fireEvent.click(await screen.findByRole('button', { name: /leave class/i }));

    await waitFor(() => {
      expect(axios.delete).toHaveBeenCalledWith(
        expect.stringContaining('/api/rooms/3704'),
        expect.any(Object)
      );
    });
  });

  test('update color sends patch request', async () => {
    vi.mocked(axios.get).mockResolvedValue({
      data: [{ crn: '3704', course_name: 'CS 3704', color: '#3b82f6', latestMessage: null }]
    });
    vi.mocked(axios.patch).mockResolvedValue({ data: {} });

    render(
      <MemoryRouter>
        <DashboardPage />
      </MemoryRouter>
    );

    await screen.findByText('CS 3704');
    const buttons = screen.getAllByRole('button');
    fireEvent.click(buttons[2]);

    const paletteButtons = screen.getAllByRole('button');
    fireEvent.click(paletteButtons[4]);

    await waitFor(() => {
      expect(axios.patch).toHaveBeenCalledWith(
        expect.stringContaining('/api/rooms/3704/color'),
        expect.objectContaining({ color: expect.any(String) }),
        expect.any(Object)
      );
    });
  });

  test('calls signOut when logout button is clicked', async () => {
    render(
      <MemoryRouter>
        <DashboardPage />
      </MemoryRouter>
    );

    const allButtons = await screen.findAllByRole('button');
    fireEvent.click(allButtons[1]);
    expect(mockSignOut).toHaveBeenCalled();
  });
});