// Generated by GitHub Copilot
import { render, screen } from '@testing-library/react';
import { vi } from 'vitest';
import App from './App';

const mockAuthState = {
  session: null as null | { user: { id: string } },
  loading: false
};

vi.mock('./context/AuthContext', () => ({
  AuthProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
  useAuth: () => mockAuthState
}));

vi.mock('./pages/LoginPage', () => ({ default: () => <div>Login Page</div> }));
vi.mock('./pages/SignupPage', () => ({ default: () => <div>Signup Page</div> }));
vi.mock('./pages/DashboardPage', () => ({ default: () => <div>Dashboard Page</div> }));
vi.mock('./pages/ChatPage', () => ({ default: () => <div>Chat Page</div> }));

describe('App routing', () => {
  beforeEach(() => {
    mockAuthState.session = null;
    mockAuthState.loading = false;
    window.history.pushState({}, '', '/');
  });

  test('renders login route at /login', async () => {
    window.history.pushState({}, '', '/login');
    render(<App />);
    expect(await screen.findByText('Login Page')).toBeInTheDocument();
  });

  test('renders loading state while session is being verified', async () => {
    mockAuthState.loading = true;
    render(<App />);
    expect(await screen.findByText('Verifying Session')).toBeInTheDocument();
  });

  test('renders dashboard for authenticated users on /', async () => {
    mockAuthState.session = { user: { id: 'u1' } };
    render(<App />);
    expect(await screen.findByText('Dashboard Page')).toBeInTheDocument();
  });
});