// Generated by GitHub Copilot
import { describe, expect, test, vi, beforeEach } from 'vitest';

const mockRender = vi.fn();
const mockCreateRoot = vi.fn(() => ({ render: mockRender }));

vi.mock('react-dom/client', () => ({
  createRoot: mockCreateRoot
}));

describe('main bootstrap', () => {
  beforeEach(() => {
    vi.resetModules();
    vi.clearAllMocks();
  });

  test('creates root and renders app when root element exists', async () => {
    document.body.innerHTML = '<div id="root"></div>';
    await import('./main');

    expect(mockCreateRoot).toHaveBeenCalled();
    expect(mockRender).toHaveBeenCalled();
  });

  test('renders fallback error UI when root element is missing', async () => {
    document.body.innerHTML = '';
    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

    await import('./main');

    expect(consoleSpy).toHaveBeenCalledWith(
      'App failed to render:',
      expect.any(Error)
    );
    expect(document.body.innerHTML).toContain('CRN Connect failed to start');
    consoleSpy.mockRestore();
  });
});