// Generated by GitHub Copilot
const express = require('express');
const request = require('supertest');

const mockState = {
  users: {},
  rooms: {},
  memberships: {}
};

jest.mock('../lib/prisma', () => ({
  user: {
    upsert: jest.fn(async ({ where, update, create }) => {
      const existing = mockState.users[where.id];
      const nextValue = existing
        ? { ...existing, ...update }
        : { id: where.id, ...create };
      mockState.users[where.id] = nextValue;
      return nextValue;
    }),
    findUnique: jest.fn(async ({ where }) => {
      const user = mockState.users[where.id];
      if (!user) return null;

      const rooms = Object.values(mockState.memberships)
        .filter((membership) => membership.user_id === where.id)
        .map((membership) => ({
          color: membership.color,
          room: {
            ...mockState.rooms[membership.crn],
            messages: []
          }
        }));

      return { ...user, rooms };
    })
  },
  cRN_Room: {
    upsert: jest.fn(async ({ where, create }) => {
      if (!mockState.rooms[where.crn]) {
        mockState.rooms[where.crn] = { crn: where.crn, course_name: create.course_name };
      }
      return mockState.rooms[where.crn];
    }),
    findUnique: jest.fn(async ({ where }) => mockState.rooms[where.crn] || null)
  },
  user_CRN_Room: {
    upsert: jest.fn(async ({ where, create }) => {
      const key = `${where.user_id_crn.user_id}:${where.user_id_crn.crn}`;
      if (!mockState.memberships[key]) {
        mockState.memberships[key] = {
          user_id: create.user_id,
          crn: create.crn,
          color: '#3b82f6'
        };
      }
      return mockState.memberships[key];
    }),
    update: jest.fn(),
    delete: jest.fn()
  },
  message: {
    findMany: jest.fn(async () => [])
  }
}));

jest.mock('../middleware/auth', () => (req, res, next) => {
  req.user = {
    id: 'integration-user',
    email: 'integration@vt.edu',
    user_metadata: {
      full_name: 'Integration User',
      avatar_url: 'https://example.com/integration.png'
    }
  };
  next();
});

const authRouter = require('../routes/auth');
const roomsRouter = require('../routes/rooms');

function createApp() {
  const app = express();
  app.use(express.json());
  app.use('/api/auth', authRouter);
  app.use('/api/rooms', roomsRouter);
  return app;
}

describe('integration workflow', () => {
  beforeEach(() => {
    mockState.users = {};
    mockState.rooms = {};
    mockState.memberships = {};
  });

  it('syncs a user, joins a room, and returns that room in dashboard list', async () => {
    const app = createApp();

    const syncRes = await request(app).post('/api/auth/sync').send({});
    expect(syncRes.status).toBe(200);
    expect(syncRes.body.id).toBe('integration-user');

    const joinRes = await request(app)
      .post('/api/rooms/join')
      .send({ crn: '3704', course_name: 'CS 3704' });
    expect(joinRes.status).toBe(200);

    const roomsRes = await request(app).get('/api/rooms');
    expect(roomsRes.status).toBe(200);
    expect(roomsRes.body).toEqual([
      {
        crn: '3704',
        course_name: 'CS 3704',
        color: '#3b82f6',
        latestMessage: null
      }
    ]);
  });
});