// Generated by GitHub Copilot
import { beforeEach, describe, expect, test, vi } from 'vitest';

const mockIo = vi.fn(() => ({ mocked: true }));

vi.mock('socket.io-client', () => ({
  io: mockIo
}));

describe('socket lib', () => {
  beforeEach(() => {
    vi.resetModules();
    vi.clearAllMocks();
  });

  test('initializes socket with expected url and autoConnect false', async () => {
    const mod = await import('./socket');

    expect(mockIo).toHaveBeenCalledWith('http://localhost:3001', {
      autoConnect: false
    });
    expect(mod.socket).toEqual({ mocked: true });
  });
});