// Generated by GitHub Copilot
import { beforeEach, describe, expect, test, vi } from 'vitest';

const mockCreateClient = vi.fn(() => ({ mocked: true }));

vi.mock('@supabase/supabase-js', () => ({
  createClient: mockCreateClient
}));

describe('supabase lib', () => {
  beforeEach(() => {
    vi.resetModules();
    vi.clearAllMocks();
  });

  test('initializes createClient with fallback values when env is missing', async () => {
    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

    const mod = await import('./supabase');

    expect(mockCreateClient).toHaveBeenCalledWith(
      'https://placeholder.supabase.co',
      'placeholder'
    );
    expect(mod.supabase).toEqual({ mocked: true });
    consoleSpy.mockRestore();
  });
});